Notify365/Notify365/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client/', views.client_view.client, name="client"),
    path('', views.index, name="dashboard"),
    path('notification/<int:notification_id>/mark_as_read/', views.mark_as_read, name='mark_as_read'),
    path('test/', views.test, name='test'),
    path('login/', views.login_view.login, name="login"),
    path('registration/', views.registration_view.registration, name="registration"),
    path('setting/', views.setting_view.setting, name="setting"),
    path('setting/account/', views.account_view.account, name="account"),
    path('setting/account/edit', views.account_view.edit_account, name="edit-account"),
    path('setting/company/', views.company_view.company, name="company"),
    path('setting/security/', views.security_view.security, name="security"),
    path('setting/notification/', views.notification_view.notification, name="notification"),

    path('customers/', views.customer_view.customer, name='customers'),
    path('customers/import/canceled', views.customer_view.cancel_customers_automatically, name='import-canceled-customers'),
    path('customers/add', views.customer_view.add_customer_view, name='add-customer'),
    path('customers/<int:customer_id>/', views.customer_view.customer_detail_view, name='customer_detail'),
    path('customers/edit/<int:id>', views.customer_view.edit_customer_view, name='edit-customer'),
    path('customers/delete/<int:id>', views.customer_view.delete_customer, name='delete-customer'),
    path('customers/filter/', views.customer_view.filter_customer_view, name='filter-customer'),

    path('customers/deal/add', views.customer_service_view.add_deal_view, name='add-deal'),
    path('customers/deal/edit/<int:id>', views.customer_service_view.edit_deal_view, name='edit-deal'),
    path('customers/deal/cancel/<int:id>', views.customer_service_view.cancel_deal_view, name='cancel-deal'),
    path('customers/deal/delete/<int:id>', views.customer_service_view.delete_deal_view, name='delete-deal'),

    path('customers/note/add', views.note_view.add_note_view, name='add-note'),
    path('customers/get/services-providers', views.customer_view.get_services_providers, name='services-providers'),
    path('customers/contact/add', views.contact_view.add_contact_view, name='add-contact'),
    path('customers/document/update', views.document_view.update_document_view, name='update-document'),
    path('customers/send/text/', views.customer_send_text_message_view.customer_send_message, name='customer-send-text'),
    path('sms/send/chat/', views.notify_view.send_message_chat, name='send-chat'),
    path('sms/<int:customer_id>/messages/', views.notify_view.load_messages, name='load-messages'),

    path('notification/', views.notify_view.notify, name="notify"),
    path('notification/search', views.notify_view.notify_filter, name="filter-call-logs"),
    path('calendar/', views.calendar_views.calendar, name='calendar'),
    path('calendar/today', views.calendar_views.day_calendar, name='day'),
    path('setting/general_settings/<str:tab>', views.general_view.GeneralSettingView.as_view(), name='general_setting'),
    path('setting/general_settings/templateCategory/add', views.general_view.add_template_category, name='template-category-add'),
    path('setting/general_settings/templateCategory/edit/<int:id>', views.general_view.edit_template_category, name='template-category-edit'),
    path('setting/general_settings/templateCategory/remove/<int:id>', views.general_view.delete_template_category, name='template-category-remove'),
    path('setting/general_settings/providerType/add', views.general_view.add_provider_type, name='provider-type-add'),
    path('setting/general_settings/providerType/edit/<int:id>', views.general_view.edit_provider_type, name='provider-type-edit'),
    path('setting/general_settings/providerType/remove/<int:id>', views.general_view.delete_provider_type, name='provider-type-remove'),
    
    path('setting/general_settings/requiredDocument/add', views.general_view.add_required_document, name='required-document-add'),
    path('setting/general_settings/requiredDocument/edit/<int:id>', views.general_view.edit_required_document, name='required-document-edit'),
    path('setting/general_settings/requiredDocument/remove/<int:id>', views.general_view.delete_required_document, name='required-document-remove'),

    path('setting/general_settings/product/add', views.product_view.add_product_view, name='product-add'),
    path('setting/general_settings/product/edit/<int:id>', views.product_view.edit_product_view, name='product-edit'),
    path('setting/general_settings/product/remove/<int:id>', views.product_view.delete_product, name='product-remove'),

    path('setting/general_settings/template/add', views.template_view.add_template_view, name='template-add'),
    path('setting/general_settings/template/edit/<int:id>', views.template_view.edit_template_view, name='template-edit'),
    path('setting/general_settings/template/remove/<int:id>', views.template_view.delete_template, name='template-remove'),

    path('setting/import/', views.import_view.data_import, name='import'),
    path('setting/import/data/', views.import_view.file_import, name='file-import'),
    
    path('save/log/call/', views.call_view.save_log_call, name="save_log_call"),
    
    # URLS CORRESPONDIENTES A LOS ENDPOINT 
    path('token/', views.call_view.get_token, name="get-token"),
    path('webcall/handle_calls/', views.call_view.call, name="call"),
    path('webcall/sms/reply/', views.call_view.sms_reply, name='sms-reply'),
    path('webcall/handle_recording/', views.call_view.handle_recording, name='handle_recording'),
    path('check_number/', views.call_view.check_number, name='check_number'),
    
    path('sms/', views.notify_view.sms, name="sms"),
    path('sms/<int:customer_id>/', views.notify_view.sms, name='sms_detail'),
    #path('notifications/get_notifications/<int:customer_id>/', views.notify_view.get_notifications, name='get_customer_messages'),

    path('login=fail/', views.login_view.my_login_view, name="my_login_view"),
    path('login=responsive/', views.login_view.responsive_login_view, name="responsive_login_view"),
    path('logout/', views.login_view.logout_view, name="logout"),
    path('setting/users/', views.user_view.UserListView.as_view(), name="users"),
    path('setting/users/new/', views.user_view.create_user, name="new-user"),
    path('setting/users/edit/<int:user_id>/', views.user_view.edit_user, name="edit-user"),
    path('setting/users/password/reset/<int:user_id>/', views.user_view.reset_password, name="reset-password"),
    path('setting/users/remove/<int:user_id>/', views.user_view.delete_user, name="delete-user"),
    path('setting/company/edit', views.company_view.edit_company, name="company-edit"),

    path('reports/', views.reports_views.reports, name="reports"),
    path('reports/clients/company/list', views.reports_views.list_client_by_company, name="list-client-by-company"),
    path('reports/clients/remarketing', views.reports_views.remarketing, name="remarketing"),
    path('reports/clients/company/total', views.reports_views.total_client_by_company, name="total-client-by-company"),
    path('reports/clients/bussines-line/total', views.reports_views.total_client_by_busines_line, name="total-client-by-business-line"),
    path('reports/clients/inactive', views.reports_views.inactive_client, name="inactive-clients"),
    path('reports/agent/messages/responded', views.reports_views.agent_communications_view, name="responded-messages-agent"),
    path('reports/agent/calls/answered', views.reports_views.agent_answered_calls_view, name="answered-calls-agent"),
    path('reports/agent/premium/balance', views.reports_views.premium_balance, name="premium-balance"),
    
   
]

Notify365/notifications/models/notification_model.py
from django.db import models
from customers.models import Customer
from security.models import CustomUser as User

import os
from django.conf import settings

class Notification(models.Model):
    EMAIL = 'email'
    TEXT = 'text'
    CALL = 'call'
    REPLY = 'reply'
    CHANNEL_CHOICES = [
        (EMAIL, 'Email'),
        (TEXT, 'Text'),
        (CALL, 'Call'),
        (REPLY, 'Reply'),
    ]

    template = models.ForeignKey('Template', on_delete=models.SET_NULL, null=True, blank=True, related_name='notifications')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='notifications', blank=True, null=True)
    date = models.DateTimeField()
    channel = models.CharField(max_length=5, choices=CHANNEL_CHOICES)
    text = models.TextField()
    sent_by = models.TextField(default='Automatic notification')
    read = models.BooleanField(default=True)
    read_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='read_notification', blank=True, null=True )
    attach = models.FileField(upload_to='static/files/notification_attach/', blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_notification', blank=True, null=True )
    to_number = models.TextField(default='', blank=True, null=True)
    from_number = models.TextField(default='', blank=True, null=True)

    def __str__(self):
        notification_message = f'Notification: '

        if self.template:
            notification_message += f'{self.template.name} for '

        notification_message += f'{self.customer} on {self.date.strftime("%m-%d-%Y")} via {self.channel}'

        return notification_message
    
    def extension(self):
        name, extension = os.path.splitext(self.attach.name)
        return extension

Notify365/notifications/models/template_model.py
from django.db import models
from simple_history.models import HistoricalRecords
from security.models import Suscription
from django.conf import settings

class Template(models.Model):
    BIRTHDAY = 'birthday'
    PENDING_DOCUMENT = 'pendingDocument'
    EXPIRY_TOMORROW = 'expiryTomorrow'
    PROMO = 'promo'
    NEXT_EXPIRY = 'nextExpiry'
    EXPIRY = 'expiry'
    PAYMENT_REMINDER = 'paymentReminder'
    SERVICE_EXPIRED = 'serviceExpired'
    SERVICE_PENDING_EXPIRED = 'servicePendingExpired'
    TYPE_CHOICES = [
        (BIRTHDAY, 'Birthday'), # Template para notificar a los clientes que cumplen años
        (PENDING_DOCUMENT, 'Pending Document'), # Template para notificar a los clientes que tengan documentos pendientes de enviar.
        (PROMO, 'Promo'), # Template para enviar promociones a los clientes
        (NEXT_EXPIRY, 'Next Expiry'), # Template para notificar a los clientes que su poliza expira en 7 dias
        (EXPIRY, 'Expiry'), # Template para notificar a los clientes que su poliza expiro hace 7 dias
        (PAYMENT_REMINDER, 'Payment Reminder'), # Template para notificar a los clientes que tienen pagos pendientes.
        (EXPIRY_TOMORROW, 'Expiry Tomorrow'), # Template para notificar a los clientes que su poliza expira el dia siguiente
        (SERVICE_EXPIRED, 'Service Expired'), # Template para notificar a los clientes que su poliza acaba de expirar.
        (SERVICE_PENDING_EXPIRED, 'Service Pending Expire'), # Template para notificar a los clientes que su poliza esta vencida pero se le daran unos dias de gracia antes de cancelarla
    ]
    
    ONCE = 'once'
    DAILY = 'Daily'
    EVERY3DAY = 'Every 3 days'
    WEEKLY = 'Weekly'
    BIWEEKLY = 'Biweekly'
    MONTHLY = 'Monthly'
    QUARTERLY = 'Quarterly'
    SEMIANUAL = 'Semi-annually'
    ANNUALLY = 'Annually'
    INTERVAL = [
        (ONCE, 'Once'),
        (DAILY, 'Daily'),
        (EVERY3DAY, 'Every 3 days'),
        (WEEKLY, 'Weekly'),
        (BIWEEKLY, 'Biweekly'),
        (MONTHLY, 'Monthly'),
        (QUARTERLY, 'Quarterly'),
        (SEMIANUAL, 'Semi-annually'),
        (ANNUALLY, 'Annually'),
    ]

    EMAIL = 'email'
    TEXT = 'text'
    CHANNEL_CHOICES = [
        (EMAIL, 'Email'),
        (TEXT, 'Text'),
    ]

    name = models.CharField(max_length=255)
    text = models.TextField()
    suscription = models.ForeignKey(Suscription, on_delete=models.CASCADE, related_name='templates')
    type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    interval = models.CharField(max_length=30, choices=INTERVAL, default=ANNUALLY)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_templates'
    )
    channel_to = models.CharField(max_length=6, choices=CHANNEL_CHOICES, default="text")
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if 'user' in kwargs:
            user = kwargs.pop('user')
            self.suscription = user.suscription
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Template: {self.name} ({self.type}) for {self.suscription}'

Notify365/settings/views/notification_view.py
from django.shortcuts import render

# Create your views here.
def notification(request):
    return render(request, "settings/notification_template.html", {})

Notify365/templates/notifications/chat_list.html
{% for customer in customers %}
    <div class="chat" data-chat="person{{ forloop.counter0|add:chatCounter }}">
        {% include 'notifications/notification_list.html' with customer=customer %}
    </div>
{% endfor %}

Notify365/templates/notifications/chat_message.html
{% load static %}
<div class="bubble me">
    {% if attach_url %}
        {% if notification.extension == '.jpg' or notification.extension  == '.jpeg' or notification.extension == '.png' or notification.extension == '.gif' %}
            <a style="text-align: -webkit-center;" href={{ attach_url }} target="_BLANK"><img class="w-full max-w-64" src="{{ attach_url }}" alt="customer-attach"></a>
            <p class="text-xs pb-5 text-center">{{ attach_name }}</p>
        {% elif notification.extension == '.pdf' %}
            <a style="text-align: -webkit-center;" href={{ attach_url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/pdf-file-icon.png' %}" alt="customer-attach"></a>
            <p class="text-xs pb-5 text-center">{{ attach_name }}</p>
        {% elif notification.extension == '.doc' or notification.extension == '.docx' %}
            <a style="text-align: -webkit-center;" href={{ attach_url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/microsoft-word-icon.png' %}" alt="customer-attach"></a>
            <p class="text-xs pb-5 text-center">{{ attach_name }}</p>
        {% else %}
            <a style="text-align: -webkit-center;" href={{ attach_url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/default-file.png' %}" alt="customer-attach"></a>
            <p class="text-xs pb-5 text-center">{{ attach_name }}</p>
        {% endif %}
    {% endif %}
    <p>{{ message_text }}</p>
    <div class="message-time">{{ message_time }}</div>
</div>


            

Notify365/templates/notifications/customer_list.html
{% load static %}
{% for customer in customers %}
    <li class="person" data-chat="person{{ forloop.counter0|add:chatCounter }}" data-id="{{ customer.id }}">
        <img src="{% static 'images/user-circle-icon.png' %}" alt="" />
        <span class="name">{{ customer.first_name }} {{ customer.last_name }}</span>
        <span class="time">
            {% if customer.notifications_list %}
                {{ customer.notifications_list.first.date|date:"H:i A" }}
            {% endif %}
        </span>
        <span class="preview">
            {% if customer.notifications_list %}
                {{ customer.notifications_list.first.text }}
            {% endif %}
        </span>
    </li>
{% endfor %}

Notify365/templates/notifications/notification_list.html
{% load static %}
<div class="conversation-start">
    {% if customer.notifications_list %}
        <span>{{ customer.notifications_list.first.date|date:"m/d/Y" }}</span>
    {% endif %}
</div>
{% for notification in customer.notifications_list %}
    <div class="bubble {% if notification.sent_by == "Customer Message" %}you{% else %}me{% endif %}">
        {% if notification.attach %}
            {% if notification.extension == '.jpg' or notification.extension  == '.jpeg' or notification.extension == '.png' or notification.extension == '.gif' %}
                <a style="text-align: -webkit-center;" href={{ notification.attach.url }} target="_BLANK"><img class="w-full max-w-64" src="{{ notification.attach.url }}" alt="customer-attach"></a>
                <p class="text-xs pb-5 text-center">{{ notification.file_name }}</p>
            {% elif notification.extension == '.pdf' %}
                <a style="text-align: -webkit-center;" href={{ notification.attach.url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/pdf-file-icon.png' %}" alt="customer-attach"></a>
                <p class="text-xs pb-5 text-center">{{ notification.file_name }}</p>
            {% elif notification.extension == '.doc' or notification.extension == '.docx' %}
                <a style="text-align: -webkit-center;" href={{ notification.attach.url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/microsoft-word-icon.png' %}" alt="customer-attach"></a>
                <p class="text-xs pb-5 text-center">{{ notification.file_name }}</p>
            {% else %}
                <a style="text-align: -webkit-center;" href={{ notification.attach.url }} target="_BLANK"><img class="w-full max-w-64" src="{% static 'images/default-file.png' %}" alt="customer-attach"></a>
                <p class="text-xs pb-5 text-center">{{ notification.file_name }}</p>
            {% endif %}
            {{ notification.text }}
        {% else %}
            {{ notification.text }}
        {% endif %}
        <div class="message-time">{{ notification.date|date:"m/d/Y H:i A" }}</div>
    </div>
{% endfor %}

Notify365/templates/notifications/text_message_template.html
{% extends "layouts/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/sms.css' %}">
{% endblock css %}
{% block title %}Notifications{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="container">
        <div class="left overflow-auto" id="customer-panel">
            <div class="top fixed">
                <input class="text-left" type="text" placeholder="Search" id="searchInput" />
            </div>
            <ul class="people" id="customerList">
               {% for customer in customers %}
                    <li class="person" data-chat="person{{ forloop.counter0|add:chatCounter }}" data-id="{{ customer.id }}">
                        <img src="{% static 'images/user-circle-icon.png' %}" alt="" />
                        <span class="name">{{ customer.first_name }} {{ customer.last_name }}</span>
                        <span class="time">
                            {% if customer.notifications_list %}
                                {{ customer.notifications_list.first.date|date:"H:i A" }}
                            {% endif %}
                        </span>
                        <span class="preview">
                            {% if customer.notifications_list %}
                                {{ customer.notifications_list.first.text }}
                            {% endif %}
                        </span>
                    </li>
                {% endfor %}
            </ul>

            <!-- Sección para mostrar el mensaje de carga mientras se cargan más clientes -->
            <div id="loading" style="display: none; text-align: center; margin-top: 10px;">
                Loading more customers...
            </div>
        </div>
        <div class="right">
            <div class="top"><span>To: <span class="name"></span></span></div>
            <div class="chat-container" id="chat-container">
                {% for customer in customers %}
                    <div class="chat {% if customer.id == selected_customer_id %}active-chat{% endif %}" data-chat="person{{ forloop.counter }}">
                        {% include 'notifications/notification_list.html' with customer=customer %}
                    </div>
                {% endfor %}
            </div>
            <form id="send-message-form" action="{% url 'send-chat' %}" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <input type="hidden" id="customer-id" name="customer-id" value="">
                <div class="write">
                    <label for="dropzone-file" class="write-link attach cursor-pointer">
                        <input id="dropzone-file" name="document-file" type="file" class="hidden" />
                        <span id="file-name" class="ml-2"></span>
                    </label>
                    <input type="text" id="message-text" name="message-text" placeholder="Write your message..." class="message-input">
                    <button type="submit" class="write-link send pr-2"></button>
                    <span class="error-message pr-2"></span>
                </div>
                <div id="error-message" class="error-message text-xl -mt-8" style="color: red; display: none;"></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/sms.js' %}"></script>
    <script type="text/javascript">
        var chatCounter = {{ customers|length }}; // Inicia el contador con el número actual de clientes
        
       document.addEventListener('DOMContentLoaded', function () {
            const sendMessageForm = document.getElementById('send-message-form');
            const textMessage = document.getElementById('message-text');
            const attach = document.getElementById('file-name'); 
            const fileInput = document.getElementById('dropzone-file');

            sendMessageForm.addEventListener('submit', function (event) {
                event.preventDefault();
                let formData = new FormData(this);
                let isValid = true;
                resetErrorMessages();

                // Validaciones de longitud y GSM-7
                if (textMessage.value.trim().length > 300) {
                    setErrorFor(textMessage, 'Message text cannot exceed 300 characters');
                    isValid = false;
                } else if (!textMessage.value.trim()) {
                    setErrorFor(textMessage, 'Message text cannot be blank');
                    isValid = false;
                } else if (fileInput.files.length > 0) {
                    const fileSize = fileInput.files[0].size; // in bytes
                    if (fileSize > 2 * 1024 * 1024) { // 2 MB in bytes
                        setErrorFor(textMessage, 'Attach file size cannot exceed 2MB');
                        isValid = false;
                    }
                } else {
                    const gsm7Validation = isGSM7(textMessage.value.trim());
                    if (!gsm7Validation.isValid) {
                        setErrorFor(textMessage, `Message text contains unsupported character: "${gsm7Validation.invalidCharacter}"`);
                        isValid = false;
                    }
                }

                if (isValid) {
                    $.ajax({
                        url: this.action,
                        type: 'POST',
                        data: formData,
                        processData: false,
                        contentType: false,
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest' 
                        },
                        success: function(response) {
                            console.log('Respuesta del servidor:', response.html);
                            if (response.html) {
                                console.log("entro aqui y debe funcoionar")
                                let activeChat = document.querySelector('.chat-container .active-chat');
                                if (activeChat) {
                                    console.log('aqui debe dibujar la vista')
                                    activeChat.insertAdjacentHTML('afterbegin', response.html);
                                    console.log(activeChat);
                                    scrollToBottom();
                                }
                                textMessage.value = ''; // Limpiar el campo
                                attach.textContent = ''; // Limpiar el campo
                                fileInput.value = '' ; // Limpiar el campo
                            }
                        },
                        error: function(xhr, status, error) {
                            console.error('Error enviando el mensaje:', error);
                            let errorMessage = document.getElementById('error-message');
                            errorMessage.style.display = 'block';
                            errorMessage.innerText = 'Error sending message. Please try again later.';
                        }
                    });
                }
            });

            function resetErrorMessages() {
                const errorMessages = document.querySelectorAll('.error-message');
                errorMessages.forEach(errorMessage => {
                    errorMessage.textContent = '';
                });
            }

            function setErrorFor(input, message) {
                const formControl = input.parentElement;
                const errorMessage = formControl.querySelector('.error-message');
                errorMessage.textContent = message;
                input.classList.add('error');
            }

            function isGSM7(text) {
                const gsm7Characters = '@£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉ !"#¤%&\'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà';
                for (let i = 0; i < text.length; i++) {
                    if (!gsm7Characters.includes(text[i])) {
                        return { isValid: false, invalidCharacter: text[i] };
                    }
                }
                return { isValid: true, invalidCharacter: null };
            }

            function scrollToBottom() {
                let activeChat = document.querySelector('.chat-container .active-chat');
                if (activeChat) {
                    activeChat.scrollTop = activeChat.scrollHeight;
                }
            }
        });

       
    </script>
{% endblock script %}